version: '3'

services:

  php:
    container_name: rahatlaticisesler-php
    build:
      context: ./docker/php
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - ./:/srv/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 123456
    networks:
      - rahatlaticisesler-app-network
    working_dir: /srv/www

  nginx:
    container_name: rahatlaticisesler-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/srv/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - rahatlaticisesler-app-network

  mysql:
    container_name: rahatlaticisesler-mysql
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 123456
    networks:
      - rahatlaticisesler-app-network

  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./:/srv/www
    working_dir: /srv/www
    command: composer install --ignore-platform-reqs

#Docker Networks
networks:
  rahatlaticisesler-app-network:
    driver: bridge
